RaidBookStore/Areas/Admin/Controllers/CoverTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using RaidBookStore.DataAccess;
using RaidBookStore.DataAccess.Repository.IRepository;
using RaidBookStore.Models;
using RaidBookStore.Utility;

namespace RaidBookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetails.Role_Admin)]

    public class CoverTypeController : Controller
    {
        //private readonly ApplicationDbContext _db;

        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }



        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType coverType)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(coverType);
                _unitOfWork.Save();
                TempData["Success"] = "Cover Type created successfully!";
                return RedirectToAction("Index");

            }
            return View(coverType);
        }

        //EDIT ------------------------------
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var coverTypeFirst = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);
            

            if (coverTypeFirst == null)
            {
                return NotFound();
            }

            return View(coverTypeFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType coverType)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(coverType);
                _unitOfWork.Save();
                TempData["Success"] = "Cover Type updated successfully!";
                return RedirectToAction("Index");

            }
            return View(coverType);
        }


        //DELETE ------------------------------
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            

            var coverTypeFirst = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);
            

            if (coverTypeFirst == null)
            {
                return NotFound();
            }

            return View(coverTypeFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var coverType = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            _unitOfWork.CoverType.Remove(coverType);
            _unitOfWork.Save();
            TempData["Success"] = "Cover Type deleted successfully!";
            return RedirectToAction("Index");

        }




    }
}

RaidBookStore/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using RaidBookStore.DataAccess;
using RaidBookStore.Models;

namespace RaidBookStore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }



        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _db.Categories;
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                //Custom Error Message
                ModelState.AddModelError("name", "Display order cannot be same with Name value.");
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Add(category);
                _db.SaveChanges();
                TempData["Success"] = "Category created successfully!";
                return RedirectToAction("Index");

            }
            return View(category);
        }

        //EDIT ------------------------------
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFind = _db.Categories.Find(id);

            //var categoryFirst = _db.Categories.FirstOrDefault(c => c.Id == id);
            //var categorySingle = _db.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryFind == null)
            {
                return NotFound();
            }

            return View(categoryFind);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                //Custom Error Message
                ModelState.AddModelError("name", "Display order cannot be same with Name value.");
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Update(category);
                _db.SaveChanges();
                TempData["Success"] = "Category updated successfully!";
                return RedirectToAction("Index");

            }
            return View(category);
        }


        //DELETE ------------------------------
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFind = _db.Categories.Find(id);

            //var categoryFirst = _db.Categories.FirstOrDefault(c => c.Id == id);
            //var categorySingle = _db.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryFind == null)
            {
                return NotFound();
            }

            return View(categoryFind);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var category = _db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            
            _db.Categories.Remove(category);
            _db.SaveChanges();
            TempData["Success"] = "Category deleted successfully!";
            return RedirectToAction("Index");

        }




    }
}

RaidBookStore/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

@{
    ViewData["Title"] = "Create";
}


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-info">Create Cover Type</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" type="text" />
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-info" style="width:150px">Create</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-warning" style="width:150px">
            Back to List
        </a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

RaidBookStore/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

@{
    ViewData["Title"] = "Delete";
}


<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-info">Delete Cover Type</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" disabled class="form-control" type="text" readonly  />
            

        </div>
      
        </div>
        <button type="submit" class="btn btn-info" style="width:150px">Delete</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-warning" style="width:150px">
            Back to List
        </a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

RaidBookStore/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

@{
    ViewData["Title"] = "Edit";
}


<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-info">Edit Cover Type</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" type="text" />
            <span asp-validation-for="Name" class="text-danger"></span>

        </div>
        
        <button type="submit" class="btn btn-info" style="width:150px">Update</button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-warning" style="width:150px">
            Back to List
        </a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

RaidBookStore/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}

@*@if (TempData["Success"] != null)
{
    <h5 class="bg-primary mt-4 rounded-5 text-center text-light" >@TempData["Success"]</h5>
}*@



<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Cover Type List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary "> <i class="bi bi-bookmark-plus"></i> &nbsp; Create New Cover Type</a>
        </div>
    </div>
</div>
<br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Category Name
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="50%">@item.Name</td> 
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a class="btn btn-warning mx-2" asp-controller="CoverType" asp-action="Edit" asp-route-id="@item.Id">
                        <i class="bi bi-pencil-square"></i>Edit</a>
                        <a class="btn btn-danger mx-2" asp-controller="CoverType" asp-action="Delete" asp-route-id="@item.Id">
                        <i class="bi bi-trash-fill"></i>DELETE</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>